# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: credit_decision.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='credit_decision.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x63redit_decision.proto\"\x81\x01\n\x15\x43reditDecisionRequest\x12\x14\n\x0c\x61pplicant_id\x18\x01 \x01(\t\x12\x0e\n\x06income\x18\x02 \x01(\x01\x12\x13\n\x0bloan_amount\x18\x03 \x01(\x01\x12\x16\n\x0e\x63redit_history\x18\x04 \x01(\x05\x12\x15\n\rdelinquencies\x18\x05 \x01(\x05\"[\n\x0e\x43reditDecision\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x15\n\rinterest_rate\x18\x02 \x01(\x01\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x12\n\nrisk_score\x18\x04 \x01(\x01\x32Y\n\x15\x43reditDecisionService\x12@\n\x13\x45valuateApplication\x12\x16.CreditDecisionRequest\x1a\x0f.CreditDecision\"\x00\x62\x06proto3'
)




_CREDITDECISIONREQUEST = _descriptor.Descriptor(
  name='CreditDecisionRequest',
  full_name='CreditDecisionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='applicant_id', full_name='CreditDecisionRequest.applicant_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='income', full_name='CreditDecisionRequest.income', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loan_amount', full_name='CreditDecisionRequest.loan_amount', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='credit_history', full_name='CreditDecisionRequest.credit_history', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delinquencies', full_name='CreditDecisionRequest.delinquencies', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=155,
)


_CREDITDECISION = _descriptor.Descriptor(
  name='CreditDecision',
  full_name='CreditDecision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='CreditDecision.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interest_rate', full_name='CreditDecision.interest_rate', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason', full_name='CreditDecision.reason', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='risk_score', full_name='CreditDecision.risk_score', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=248,
)

DESCRIPTOR.message_types_by_name['CreditDecisionRequest'] = _CREDITDECISIONREQUEST
DESCRIPTOR.message_types_by_name['CreditDecision'] = _CREDITDECISION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreditDecisionRequest = _reflection.GeneratedProtocolMessageType('CreditDecisionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREDITDECISIONREQUEST,
  '__module__' : 'credit_decision_pb2'
  # @@protoc_insertion_point(class_scope:CreditDecisionRequest)
  })
_sym_db.RegisterMessage(CreditDecisionRequest)

CreditDecision = _reflection.GeneratedProtocolMessageType('CreditDecision', (_message.Message,), {
  'DESCRIPTOR' : _CREDITDECISION,
  '__module__' : 'credit_decision_pb2'
  # @@protoc_insertion_point(class_scope:CreditDecision)
  })
_sym_db.RegisterMessage(CreditDecision)



_CREDITDECISIONSERVICE = _descriptor.ServiceDescriptor(
  name='CreditDecisionService',
  full_name='CreditDecisionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=250,
  serialized_end=339,
  methods=[
  _descriptor.MethodDescriptor(
    name='EvaluateApplication',
    full_name='CreditDecisionService.EvaluateApplication',
    index=0,
    containing_service=None,
    input_type=_CREDITDECISIONREQUEST,
    output_type=_CREDITDECISION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CREDITDECISIONSERVICE)

DESCRIPTOR.services_by_name['CreditDecisionService'] = _CREDITDECISIONSERVICE

# @@protoc_insertion_point(module_scope)
